### ISSUE TITLE
Add cluegen.Iter

### ISSUE THREAD

**Issue by Martmists-GH** [dabeaz/cluegen#1]
Having an easy way to iterate over an object or an object's properties would be a great addition.

Examples of how this could be implemented:
```python
# Iterating over a list of all properties
class Point3D(cluegen.Init, cluegen.Iter):
    x: int
    y: int
    z: int

point = Point3D(10, 5, 10)
for item in point:
    print(item)
# 10
# 5
# 10
```

Alternatively:
```python
# Iterating over a certain property
class RecordManager(cluegen.Iter["records"]):
    def __init__(self):
        self.records = load_from_file()

rm = RecordManager()
for record in rm:
    print(record)
# {"username": "martmists", "points": 123}
# {"username": "dabeaz", "points": 456}
```

**Comment by dabeaz** [comment]
Interesting idea. Yes.

**Comment by dabeaz** [comment]
I added an Iter class that covers the first case.  For the second (iterating over a specific field), I feel like that is easy enough to do just by defining your own __iter__() method.    So, I'll probably hold off on that for now.
