### ISSUE TITLE
Don't forget to call super in __init__ and __init_subclass__

### ISSUE THREAD

**Issue by NeilGirdhar** [dabeaz/cluegen#3]
Very cool project!  Love the simplicity.  Is there any problem with calling `super` in `__init__` and `__init_subclass__`?  If you don't, it will be impossible to use this in cooperative inheritance.

**Comment by dabeaz** [comment]
Unlike most other software, cluegen is not a package that you install and use.  It's code that you take home and own. Like a puppy.  As the owner, you're free to tie as many `super()` calls onto it as you want.
