### ISSUE TITLE
Minor point with Nodum class in README

### ISSUE THREAD

**Issue by ColMcp** [dabeaz/cluegen#8]
This is a minor point regarding one of the README examples.  It's probably too trivial to call it a bug but it might help anyone else following the "true story of developer Dave".

The final line of the `__init__()` method in class `Nodum` is:
    `return f'def __init__(self, {args}, *, lineno=None):\n{body}\n'`
If one of Nodum's subclasses doesn't have any type-hinted attributes then `args` is empty and the comma following its use causes a syntax error when an instance of the subclass in question is created. (My subclass was for recording the use of the valueless 'nil' literal in the language being compiled.)

I replaced the above line with the distinctly less elegant:
    `return f'def __init__(self, {args}{"," if len(args) > 0 else ""} *, lineno=None):\n{body}\n'`

**Comment by dabeaz** [comment]
Ah.  Good catch!

**Comment by ColMcp** [comment]
I copied your fix to my example and it works fine.
